// Generated by Wrangler on Tue Apr 01 2025 17:36:10 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
    TURNSTILE_SECRET: string
    DISCORD_BOT_TOKEN: string
    CONTENTFUL_CMA_TOKEN: string
    CONTENTFUL_CDA_TOKEN: string
    CONTENTFUL_SPACE_ID: string
    NOTION_SECRET: string
    ADMIN_USERNAME: string
    ADMIN_PASSWORD: string
}
